name: Docker Image Varnish
on:
  push:
    paths:
      - .trigger
      - Dockerfile
      - .github/workflows/*dnsmasq*

jobs:
  varnish:
    name: Dnsmasq
    runs-on: ubuntu-latest

    steps:
      - run: sudo chown runner:docker /var/run/docker.sock
        if: ${{ env.ACT }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/rollupdev/dnsmasq:latest
